### ISSUE TITLE
Add a Learn more page

### ISSUE THREAD

**Issue by csgeeek** [Yaswanth820/Ambulance-tracker#15]
On the Signup page, the `learn more` link redirects to nowhere. Create a simple learn more page and add some basic details and link it.

**Refer to**: - [Link](https://react-amb-driver.herokuapp.com/signup)

These changes are only for **Web/clients directory**

**Comment by Sakshi-75** [comment]
Hi @Yaswanth820 ,
Can I work on this?

**Comment by csgeeek** [comment]
Sure @Sakshi-75 . Assigned it to you.

**Comment by Sakshi-75** [comment]
Hi @Yaswanth820 ,
I was following the readme file and I'm getting this error when trying to run the app: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

Can you let me know if any other steps are required to start?

**Comment by csgeeek** [comment]
Hey @Sakshi-75 . The error you are getting is due to not specifying the database URL(DB_URI). I have stored it in the `.env` files which is not present in this repo. That's why it's throwing the above error (unable to connect to database). 

This issue is only related to the front-end and not to the back-end. More specifically the issue is related to `Web/clients/amb-driver/src/components/SignupForm.js`. The `Learn more` link redirects nowhere. So you just have to create a Learn More page. 

You have to create a `Learn More component page`.

Please feel free to discuss any issues you are facing. ✌

**Comment by Sakshi-75** [comment]
Hi @Yaswanth820 ,
Can you let me know what content to add in the Learn more page or would adding content be handled as a separate issue?

**Comment by csgeeek** [comment]
> Hi @Yaswanth820 , Can you let me know what content to add in the Learn more page or would adding content be handled as a separate issue?

On learn more page, you can add details like, Signing up drivers can only be done by Administrators. To add a user, please contact the administrator of this project at [Link](https://yaswanth820.github.io/my-portfolio-site/)
