### ISSUE TITLE
Create a docker file to run the project🐳

### ISSUE THREAD

**Issue by csgeeek** [Yaswanth820/Ambulance-tracker#17]
Create a `Dockerfile` 🐳 for the project. The goal here is to be able to run the project using a single command using `docker-compose`. 

**Write a simple dockerfile and expose the ports as follows**:- 

1. `amb-driver` ==> 3000
2. `hospital-display` ==> 3001
3. `admin` ==> 3002
4. Socket/Auth server ==> 5000

**Note:-** These changes are only for **Web/clients and server directories**.

**Comment by ocdbytes** [comment]
Sir,
Please assign this issue to me. I have worked with Docker/Kubernetes and have a beginner level certification.

**Comment by csgeeek** [comment]
Sure @Arun89-crypto . Done.

**Comment by ocdbytes** [comment]
PR made sir #18

**Comment by Yaswanth820** [comment]
Hey @Arun89-crypto . It looks good. 

Can you make a few more changes by setting up environmental variables in the `Dockerfile`?

**List of changes:-**

1. An env variable for MONGO_INITDB_ROOT_USERNAME: ${USERNAME}
2. MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
3. DB_URI="${DB_URI}"

**Comment by ocdbytes** [comment]
Changes done as requested. @Yaswanth820

**Comment by ocdbytes** [comment]
Sir can you please add hacktoberfest-accepted label to my PR so that it can be accepted. @Yaswanth820

**Comment by csgeeek** [comment]
Yeah sure!
