### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by AnupeshVerma** [Yaswanth820/Ambulance-tracker#25]
Please assign me this task .

**Comment by pranavjainjs** [comment]
what is this issue?

**Comment by Yogeshlodhi** [comment]
What kind of tempelate can you please elaborate the issue?

**Comment by csgeeek** [comment]
Firstly, it is a no-code task. It is for customizing the default issue template. 
We can modify the issue template to our own specific needs.

Refer to the [link](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
